let positions = [
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":0,
        "speed":1.1,
        "time":"2023-05-05T00:00:00.000Z",
        "coordinates":[
            83,
            247
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":0,
        "speed":2.2,
        "time":"2023-05-05T00:00:01.000Z",
        "coordinates":[
            103,
            247
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":0,
        "speed":4.3,
        "time":"2023-05-05T00:00:01.500Z",
        "coordinates":[
            120,
            247
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":0,
        "speed":9.5,
        "time":"2023-05-05T00:00:02.500Z",
        "coordinates":[
            137,
            249
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":1,
        "speed":25.5,
        "time":"2023-05-05T00:00:03.000Z",
        "coordinates":[
            162,
            247
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":1,
        "speed":23.2,
        "time":"2023-05-05T00:00:04.500Z",
        "coordinates":[
            177,
            248
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":5,
        "speed":24.5,
        "time":"2023-05-05T00:00:05.500Z",
        "coordinates":[
            195,
            248
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":5,
        "speed":25.2,
        "time":"2023-05-05T00:00:06.000Z",
        "coordinates":[
            218,
            249
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":6,
        "speed":25.2,
        "time":"2023-05-05T00:00:06.500Z",
        "coordinates":[
            240,
            249
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":6,
        "speed":26.7,
        "time":"2023-05-05T00:00:07.000Z",
        "coordinates":[
            258,
            247
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":7,
        "speed":25.2,
        "time":"2023-05-05T00:00:08.000Z",
        "coordinates":[
            280,
            248
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":7,
        "speed":26.1,
        "time":"2023-05-05T00:00:08.500Z",
        "coordinates":[
            303,
            248
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":6,
        "speed":26.2,
        "time":"2023-05-05T00:00:09.000Z",
        "coordinates":[
            319,
            247
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":6,
        "speed":26.7,
        "time":"2023-05-05T00:00:09.500Z",
        "coordinates":[
            338,
            247
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":7,
        "speed":26.6,
        "time":"2023-05-05T00:00:10.500Z",
        "coordinates":[
            362,
            249
        ]
    },
    {
        "athlete":{
            "lastName":"Fraser-Pryce",
            "firstName":"Shelly-Ann"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":7,
        "speed":26.1,
        "time":"2023-05-05T00:00:11.500Z",
        "coordinates":[
            380,
            247
        ]
    },




    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":0,
        "speed":1.1,
        "time":"2023-05-05T00:00:00.000Z",
        "coordinates":[
            82,
            244
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":0,
        "speed":2.2,
        "time":"2023-05-05T00:00:01.000Z",
        "coordinates":[
            102,
            244
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":0,
        "speed":4.3,
        "time":"2023-05-05T00:00:01.500Z",
        "coordinates":[
            117,
            244
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":1,
        "gapToLeader":0,
        "speed":9.5,
        "time":"2023-05-05T00:00:02.500Z",
        "coordinates":[
            137,
            243
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":1,
        "speed":25.5,
        "time":"2023-05-05T00:00:03.000Z",
        "coordinates":[
            160,
            243
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":1,
        "speed":23.2,
        "time":"2023-05-05T00:00:04.500Z",
        "coordinates":[
            183,
            243
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":5,
        "speed":24.5,
        "time":"2023-05-05T00:00:05.500Z",
        "coordinates":[
            198,
            243
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":5,
        "speed":25.2,
        "time":"2023-05-05T00:00:06.000Z",
        "coordinates":[
            219,
            242
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":6,
        "speed":25.2,
        "time":"2023-05-05T00:00:06.500Z",
        "coordinates":[
            237,
            242
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":6,
        "speed":26.7,
        "time":"2023-05-05T00:00:07.000Z",
        "coordinates":[
            257,
            242
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":7,
        "speed":25.2,
        "time":"2023-05-05T00:00:08.000Z",
        "coordinates":[
            277,
            243
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":7,
        "speed":26.9,
        "time":"2023-05-05T00:00:08.500Z",
        "coordinates":[
            301,
            242
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":6,
        "speed":26.6,
        "time":"2023-05-05T00:00:09.000Z",
        "coordinates":[
            321,
            242
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":6,
        "speed":26.7,
        "time":"2023-05-05T00:00:09.500Z",
        "coordinates":[
            342,
            244
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":7,
        "speed":26.4,
        "time":"2023-05-05T00:00:10.500Z",
        "coordinates":[
            362,
            244
        ]
    },
    {
        "athlete":{
            "lastName":"Hobbs",
            "firstName":"Aleia"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":2,
        "gapToLeader":7,
        "speed":26.8,
        "time":"2023-05-05T00:00:11.500Z",
        "coordinates":[
            376,
            244
        ]
    },

    



    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":0,
        "speed":1.1,
        "time":"2023-05-05T00:00:00.000Z",
        "coordinates":[
            78,
            239
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":0,
        "speed":2.2,
        "time":"2023-05-05T00:00:01.000Z",
        "coordinates":[
            102,
            239
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":0,
        "speed":4.3,
        "time":"2023-05-05T00:00:01.500Z",
        "coordinates":[
            122,
            239
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":0,
        "speed":9.5,
        "time":"2023-05-05T00:00:02.500Z",
        "coordinates":[
            143,
            238
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":1,
        "speed":25.5,
        "time":"2023-05-05T00:00:03.000Z",
        "coordinates":[
            163,
            237
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":1,
        "speed":23.2,
        "time":"2023-05-05T00:00:04.500Z",
        "coordinates":[
            182,
            237
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":5,
        "speed":24.5,
        "time":"2023-05-05T00:00:05.500Z",
        "coordinates":[
            196,
            239
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":5,
        "speed":25.2,
        "time":"2023-05-05T00:00:06.000Z",
        "coordinates":[
            219,
            237
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":6,
        "speed":25.2,
        "time":"2023-05-05T00:00:06.500Z",
        "coordinates":[
            240,
            238
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":6,
        "speed":26.2,
        "time":"2023-05-05T00:00:07.000Z",
        "coordinates":[
            261,
            237
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":7,
        "speed":25.2,
        "time":"2023-05-05T00:00:08.000Z",
        "coordinates":[
            276,
            238
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":7,
        "speed":26.9,
        "time":"2023-05-05T00:00:08.500Z",
        "coordinates":[
            297,
            237
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":6,
        "speed":26.2,
        "time":"2023-05-05T00:00:09.000Z",
        "coordinates":[
            320,
            237
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":6,
        "speed":26.8,
        "time":"2023-05-05T00:00:09.500Z",
        "coordinates":[
            343,
            237
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":7,
        "speed":26.9,
        "time":"2023-05-05T00:00:10.500Z",
        "coordinates":[
            359,
            238
        ]
    },
    {
        "athlete":{
            "lastName":"Jackson",
            "firstName":"Shericka"
        },
        "race":{
            "meeting":{
                "name":"Wanda Diamond League",
                "startDate":"2023-05-05"
            },
            "plannedStartTime":"2023-05-05T19:35:00Z"
        },
        "rank":3,
        "gapToLeader":7,
        "speed":27,
        "time":"2023-05-05T00:00:11.500Z",
        "coordinates":[
            376,
            237
        ]
    }
    
    

    
]